### ISSUE TITLE
Sometimes after a battle, only one of the two units gets a damage number above its head

### ISSUE THREAD

**Issue by armsnyder** [armsnyder/countermelody#223]

**Comment by cegrief** [comment]
heisenbug..

**Comment by cegrief** [comment]
jk, stalking this bug again

**Comment by cegrief** [comment]
found it. Actionpoints don't get reset until its your turn, and the unit won't deal damage if it doesn't have any actionpoints. That seems wrong, since we aren't even using that stat. 

I'm going to remove the check. If you think i should make them regenerate every turn instead of only your turn, i can look into that too.
