### ISSUE TITLE
Generate a NoteMissMessage when the player lets a note pass the target without hitting it (currently, a NoteMissMessage is only generated if the player strums and fails to hit a note that way)

### ISSUE THREAD

**Issue by armsnyder** [armsnyder/countermelody#86]

**Comment by cegrief** [comment]
Open to different ways of doing this, but my current plan is to send a message from the noteobject with just the instrumentID (because that should be 1:1 with the playernumber?) when the object is destroyed after falling too far. 

I also considered sending a reference to the noteobjects note field, which i could then use to search through each players set of notes. Let me know if that one seems better.

**Comment by cegrief** [comment]
Or should the NoteObject even raise messages? Maybe I should just handle this entirely in the battlemanager, and check if the notes have gone below the line there.

**Comment by armsnyder** [comment]
Problem: The battle ends before the last few notes are destroyed.

At the moment, there is a public method in Song.cs called GetHitNotes, which is used by BattleManager.cs to ask which notes a player could be trying to hit when they strum. As such, Song.cs has a private field called battleWindow (yeah, kinda weird this is defined in Song.cs... oh well.)

Perhaps you could rig Song.cs to send a NotePassMessage when a note exits its battlewindow? Then have BattleManager listen for the message and mark the note as missed if it hasn't already been hit?

**Comment by cegrief** [comment]
Let me take a look, that makes sense i think

**Comment by cegrief** [comment]
What value should i choose for "mark as missed"

**Comment by armsnyder** [comment]
idk... -1? 2? 42?
